### ISSUE TITLE
Bug in USM allocator exercise

### ISSUE THREAD

**Issue by illuhad** [ENCCS/sycl-workshop#16]
Hi!

I believe the USM allocator exercise for day 1/07 contains illegal code, because it attempts to use `std::vector` in device code.

This was originally reported to the hipSYCL issue tracker; you can find more details there https://github.com/illuhad/hipSYCL/issues/817

**Comment by robertodr** [comment]
Thank you! It worked when I tested it, so I guess I was very lucky. I was indeed a bit surprised, but didn't dive deeper...
