### ISSUE TITLE
Issue with CMakeLists in day-1/02_custom_selectors

### ISSUE THREAD

**Issue by zhmurov** [ENCCS/sycl-workshop#2]
In the repo with example code, the content/code/day-1/02_custom-selectors/CMakeLists.txt` file is a sym-link to itself

**Comment by mabraham** [comment]
The example cmake command targets omp only

**Comment by mabraham** [comment]
I think this exercise brings in too much incidental complexity (string parsing, what score values might mean what) for an in-class exercise where the complexity of choosing devices from different vendors probably doesn't exist. Makes good sense as extension material.
